### ISSUE TITLE
[Suggestion] Keep track of where you were when communication error occurs.

### ISSUE THREAD

**Issue by MostHated** [amzon-ex/gdrive-tree#1]
Hey there,
    I was trying to use this, but unfortunately, have ended up with a communication error mid way through, it's been 4-5 tries now but it always ends up getting some sort of issue to keep from making it through all the files (over 1tb total). I don't know the fesability of this, but it would be great to be able to, upon connection error, dump out the data already collected then start back where it left off. 

Thanks,
-MH

**Comment by amzon-ex** [comment]
@MostHated Is it possible to provide the details of the error(s) you've encountered? Would help me catch them and maybe incorporate your suggestion henceforth.

**Comment by MostHated** [comment]
Sure thing. I will try to run it again tomorrow or before I head to bed soon and see if it occurs again, it took probably 30-45 minutes before it occurred if I am not mistaken and I don't believe I made a note of the specifics last time.

**Comment by amzon-ex** [comment]
Closing because of lack of progress and repro.

**Comment by amzon-ex** [comment]
Closing because of lack of progress and repro.
